/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.foulefactory.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CsvFileWriterServiceModel 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4717947334798716702L;
    private int idProject;
    private String file;
    private boolean header;
    private String separator;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("IdProject")
    public int getIdProject ( ) { 
        return this.idProject;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("IdProject")
    public void setIdProject (int value) { 
        this.idProject = value;
        notifyObservers(this.idProject);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("File")
    public String getFile ( ) { 
        return this.file;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("File")
    public void setFile (String value) { 
        this.file = value;
        notifyObservers(this.file);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Header")
    public boolean getHeader ( ) { 
        return this.header;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Header")
    public void setHeader (boolean value) { 
        this.header = value;
        notifyObservers(this.header);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Separator")
    public String getSeparator ( ) { 
        return this.separator;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Separator")
    public void setSeparator (String value) { 
        this.separator = value;
        notifyObservers(this.separator);
    }
 
}
 