/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.foulefactory.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TaskValidationWriterServiceModel 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5408710585454892008L;
    private Integer idTask;
    private String state;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("IdTask")
    public Integer getIdTask ( ) { 
        return this.idTask;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("IdTask")
    public void setIdTask (Integer value) { 
        this.idTask = value;
        notifyObservers(this.idTask);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("State")
    public String getState ( ) { 
        return this.state;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("State")
    public void setState (String value) { 
        this.state = value;
        notifyObservers(this.state);
    }
 
}
 