/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.foulefactory.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TaskLinesWriterServiceModel 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5095693377974794766L;
    private int idProject;
    private List<String> taskColumns;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("IdProject")
    public int getIdProject ( ) { 
        return this.idProject;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("IdProject")
    public void setIdProject (int value) { 
        this.idProject = value;
        notifyObservers(this.idProject);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("TaskColumns")
    public List<String> getTaskColumns ( ) { 
        return this.taskColumns;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("TaskColumns")
    public void setTaskColumns (List<String> value) { 
        this.taskColumns = value;
        notifyObservers(this.taskColumns);
    }
 
}
 